### ISSUE TITLE
ValueError: Unknown keyword argument: snapshots_name

### ISSUE THREAD

**Issue by rackerroush** [racker/liam#7]
This is currently happening on the fix_arns branch.  Let me know if I can provide more info that would be helpful.

DEBUG:liam:Scan of elasticache:us-east-1:snapshots
Traceback (most recent call last):
  File "./neesonv2.py", line 123, in <module>
    main()
  File "./neesonv2.py", line 119, in main
    print(i_will_find_you(o))
  File "./neesonv2.py", line 107, in i_will_find_you
    results = scanner.scan()
  File "/Users/hdsiles/virtenv/neeson/lib/python3.6/site-packages/liam-0.0.1-py3.6.egg/liam/__init__.py", line 70, in scan
    for item in collection_iterator:
  File "/Users/hdsiles/virtenv/neeson/lib/python3.6/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/Users/hdsiles/virtenv/neeson/lib/python3.6/site-packages/boto3/resources/collection.py", line 168, in pages
    for item in self._handler(self._parent, params, page):
  File "/Users/hdsiles/virtenv/neeson/lib/python3.6/site-packages/boto3/resources/response.py", line 246, in __call__
    identifiers, response_item))
  File "/Users/hdsiles/virtenv/neeson/lib/python3.6/site-packages/boto3/resources/response.py", line 295, in handle_response_item
    resource = resource_cls(**kwargs)
  File "/Users/hdsiles/virtenv/neeson/lib/python3.6/site-packages/boto3/resources/base.py", line 111, in __init__
    raise ValueError('Unknown keyword argument: {0}'.format(name))
ValueError: Unknown keyword argument: snapshots_name

**Comment by Gifflen** [comment]
Thanks for that justin, Will take a look at this soon
